baseurl = "owlsec-technologies.netlify.com"
languageCode = "en-us"
languageLang = "en"
title = "OwlSec Technologies"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
disableKinds = ["taxonomyTerm"]
[Taxonomies]
category = "thinks/categories"
[permalinks]
  categories = "thinks/categories/:slug/"
